server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    drive-class-name: org.postgresql.Drive
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0
